#!/usr/bin/env python
"""toggle a dynamic service firewall on/off

Usage: %s DEVICE "up|down|status|list"
where DEVICE is a network interface, such as wlan0
This script starts or stops a firewall as defined in servicewall.py
"""

#from statefulfirewall import StateFulFireWall
import servicewall
from servicewall import network_helpers
from sys import argv
from os import environ


if __name__ == "__main__":

    # Normalize the way networkd-dispatcher launches this script :
    state_flag = environ["STATE"]
    if state_flag == "routable":
        argv = [argv[0], environ["IFACE"], "up"]

    if len(argv) != 3:
        raise SystemError("wrong number of arguments : %s" % " ".join(argv))
    device = argv[1]
    action = argv[2]
    firewall = servicewall.ServiceWall()

    if action == "up":
        if firewall.up:
            raise SystemExit()
        firewall.start()

    elif action == "down":
        if not firewall.up:
            raise SystemExit()
        firewall.stop()

    elif action == "connectivity-change":
        if firewall.up:
            local_subnet = network_helpers.get_subnetwork()
            if local_subnet != firewall.subnetwork:
                firewall.down()
                firewall.up()

    elif action == "status":
        if firewall.up:
            print("up")
        else:
            print("down")

    else:
        raise SystemError("wrong usage : %s" % " ".join(argv))

